function GUI = GUI_Plot_Modes(fig)
%% Pre-setting
Version = '1.0.4';

%% Add base layout
MainLayout = uix.VBoxFlex(...
    'Parent',fig,...
    'Spacing',1,...
    'Padding',3);

ModeListPanel = uix.BoxPanel( ...
    'Parent',MainLayout,...
    'Title','Mode List','FontSize',14);

PlotPanel = uix.BoxPanel( ...
    'Parent',MainLayout,...
    'Title','Plotting selection','FontSize',14);

% buttom
ButtonBox = uix.HBox('Parent',MainLayout,...
                     'Padding', 1, 'Spacing', 1);

set(MainLayout,'Heights',[-1,165,30])

%% ModeListPanel
ModeList = [0,0,0];
cnames  = {'Index','Freq.','Norm 1D','Norm 2D','Mu Int',  'Mu x',  'Mu y',  'Mu z','Norm[A]', 'A p1', 'A p2', 'A p3'};
cformat = {'short', 'bank',   'bank',   'bank',  'bank', 'short', 'short', 'short',   'bank','short','short','short'};
cwidth  = {     40,     50,       60,       60,      50,      60,      60,      60,       50,     60,     60,     60};

% cformat = {'short','bank' ,'short'   ,'short' ,'short' ,'short'  ,'short','short'};
% cwidth  = {     40,     50,'auto'    ,'auto'  ,'auto'  ,'auto'   ,'auto' ,'auto' };

ModeListLayout = uix.VBox('Parent',ModeListPanel,...
                           'Padding', 3, 'Spacing', 3);

hT = uitable('Parent', ModeListLayout, ...
             'Data', ModeList,...
             'ColumnName',cnames,...
             'ColumnFormat',cformat,...
             'ColumnWidth',cwidth,...
             'tag','ModeList',...
             'CellSelectionCallback',@(hObject,eventdata)Plot_Modes('uitable_CellSelectionCallback',hObject,eventdata,guidata(hObject)));

SortIndBox = uix.HBox('Parent',ModeListLayout,...
                       'Padding', 1, 'Spacing', 1);

    uicontrol('Parent',SortIndBox,...
              'Style','text',...
              'String','Sort by column: ',...
              'HorizontalAlignment','left',...
              'units', 'normalized',...
              'fontunits', 'point', 'fontsize', 14);
    uicontrol('Parent',SortIndBox,...
              'Style','popup',...
              'String',cnames,...
              'Value',3,...
              'tag','SortInd',...
              'HorizontalAlignment','left',...
              'units', 'normalized',...
              'fontunits', 'point', 'fontsize', 14);
    uicontrol('Parent', SortIndBox, ...
              'String', 'Sort',...
              'fontunits', 'point', 'fontsize', 14,...
              'Callback',@(hObject,eventdata)Plot_Modes('uitable_SortCallback',hObject,eventdata,guidata(hObject)));
    uicontrol('Parent', SortIndBox, ...
              'String', 'Refresh',...
              'fontunits', 'point', 'fontsize', 14,...
              'Callback',@(hObject,eventdata)Plot_Modes('Update_Modes',hObject,eventdata,guidata(hObject)));
 
    set(SortIndBox,'Widths',[120,-1,80,80])        
    
set(ModeListLayout,'Heights',[-1,25])
         
%% PlotPanel
PlotPanelLayout = uix.VBox('Parent',PlotPanel,...
                           'Padding', 3, 'Spacing', 3);
                
    ModeBox = uix.HBox('Parent',PlotPanelLayout,...
                        'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',ModeBox,...
                  'Style','checkbox',...
                  'String','Plot',...
                  'Value',1,...
                  'Tag','Mu_Alpha_Plot',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',ModeBox,...
                  'Style','popupmenu',...
                  'Tag','Mu_Alpha_Type',...
                  'Value',2,...
                  'String',{'Local mode', 'Exciton mode'},...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',ModeBox,...
                  'Style','text',...
                  'String',', index:',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',ModeBox,...
                  'Style','edit',...
                  'Tag','Mu_Alpha_Ind',...
                  'String','',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(ModeBox,'Widths',[50,150,60,-1])
    
    TDV_ModeScaleBox = uix.HBox('Parent',PlotPanelLayout,...
                            'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',TDV_ModeScaleBox,...
                  'Style','checkbox',...
                  'String','Transition Dipole Vectors,',...
                  'Value',1,...
                  'Tag','TDV_Plot',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);     
        uicontrol('Parent',TDV_ModeScaleBox,...
                  'Style','text',...
                  'String','Scale:',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);     
        uicontrol('Parent',TDV_ModeScaleBox,...
                  'Style','edit',...
                  'String','1',...
                  'tag','TDV_Scale',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uix.Empty('Parent',TDV_ModeScaleBox)

    set(TDV_ModeScaleBox,'Widths',[200,60,60,-1])
        
    Raman_ModeScaleBox = uix.HBox('Parent',PlotPanelLayout,...
                            'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Raman_ModeScaleBox,...
                  'Style','checkbox',...
                  'String','Raman Tensors,',...
                  'Value',1,...
                  'Tag','Raman_Plot',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);     
        uicontrol('Parent',Raman_ModeScaleBox,...
                  'Style','text',...
                  'String','Scale:',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);     
        uicontrol('Parent',Raman_ModeScaleBox,...
                  'Style','edit',...
                  'String','1',...
                  'tag','Raman_Scale',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uix.Empty('Parent',Raman_ModeScaleBox)
        uicontrol('Parent',Raman_ModeScaleBox,...
                  'Style','text',...
                  'String','Display type:',...
                  'HorizontalAlignment','right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);   
        uicontrol('Parent',Raman_ModeScaleBox,...
                  'Style','popupmenu',...
                  'Tag','Raman_Type',...
                  'Value',2,...
                  'String',{'Arrow(Not working)','Disk','Ellipsoid','Hyper Ellipsoid'},...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(Raman_ModeScaleBox,'Widths',[200,60,60,-1,90,150])    

    uicontrol('Parent',PlotPanelLayout,...
              'Style','checkbox',...
              'String','Normalize modes for direction comparison,',...
              'Value',0,...
              'Tag','Normalize',...
              'HorizontalAlignment','left',...
              'units', 'normalized',...
              'fontunits', 'point', 'fontsize', 14);
                 
    EigenVecBox = uix.HBox('Parent',PlotPanelLayout,...
                        'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',EigenVecBox,...
                  'Style','checkbox',...
                  'String','Plot mixing coefficients for exciton mode #:',...
                  'Value',0,...
                  'Tag','Plot_EigenVec',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',EigenVecBox,...
                  'Style','edit',...
                  'Tag','EigneVec_Ind',...
                  'String','',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(EigenVecBox,'Widths',[300,-1])
          
set(PlotPanelLayout,'Heights',[-1,-1,-1,-1,-1])

%% Button Box
uicontrol('Parent', ButtonBox, ...
          'String', 'Plot selected modes',...
          'fontunits', 'point', 'fontsize', 14,...
          'Callback',@(hObject,eventdata)Plot_Modes('Update_Figure',hObject,eventdata,guidata(hObject)));

uicontrol('Parent', ButtonBox, ...
          'String', 'Export handles',...
          'fontunits', 'point', 'fontsize', 14,...
          'Callback',@(hObject,eventdata)Plot_Modes('Export_Handle_Callback',hObject,eventdata,guidata(hObject)));
        
uicontrol('Parent',ButtonBox,...
          'Style','text',...
          'String',['Plot_Mode Version: v',Version],...
          'HorizontalAlignment','Center',...
          'units', 'normalized',...
          'fontunits', 'point', 'fontsize', 14);        
      
%% output handles
GUI = guihandles(fig);