function E3 = EPolar3(O_Pu1,O_Sig,O_Vi)
%EPOLAR3
%    E3 = EPOLAR3(O_PU1,O_SIG,O_VI)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Nov-2016 18:37:46

t2 = cos(O_Sig);
t3 = cos(O_Vi);
t4 = cos(O_Pu1);
t5 = sin(O_Pu1);
t6 = sin(O_Vi);
t7 = sin(O_Sig);
E3 = [t2.*t3.*t4,t2.*t3.*t5,t2.*t4.*t6,t2.*t5.*t6,t3.*t4.*t7,t3.*t5.*t7,t4.*t6.*t7,t5.*t6.*t7];
