function E2 = EPolar2(O_Sig,O_Vi)
%EPOLAR2
%    E2 = EPOLAR2(O_SIG,O_VI)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Dec-2016 15:20:39

t2 = cos(O_Sig);
t3 = cos(O_Vi);
t4 = sin(O_Sig);
t5 = sin(O_Vi);
E2 = [t2.*t3,t2.*t5,t3.*t4,t4.*t5];
