function E5 = EPolar5(P_Sum,P_Vis,P_Probe,P_Pump2,P_Pump1)
%EPOLAR5
%    E5 = EPOLAR5(O_PR,O_PU1,O_PU2,O_SIG,O_VI)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Nov-2016 18:37:46

t2 = cos(P_Probe);
t3 = cos(P_Pump2);
t4 = cos(P_Sum);
t5 = cos(P_Vis);
t6 = cos(P_Pump1);
t7 = sin(P_Pump1);
t8 = sin(P_Pump2);
t9 = sin(P_Probe);
t10 = sin(P_Vis);
t11 = sin(P_Sum);
E5 = [t2.*t3.*t4.*t5.*t6,t2.*t3.*t4.*t5.*t7,t2.*t4.*t5.*t6.*t8,t2.*t4.*t5.*t7.*t8,t3.*t4.*t5.*t6.*t9,t3.*t4.*t5.*t7.*t9,t4.*t5.*t6.*t8.*t9,t4.*t5.*t7.*t8.*t9,t2.*t3.*t4.*t6.*t10,t2.*t3.*t4.*t7.*t10,t2.*t4.*t6.*t8.*t10,t2.*t4.*t7.*t8.*t10,t3.*t4.*t6.*t9.*t10,t3.*t4.*t7.*t9.*t10,t4.*t6.*t8.*t9.*t10,t4.*t7.*t8.*t9.*t10,t2.*t3.*t5.*t6.*t11,t2.*t3.*t5.*t7.*t11,t2.*t5.*t6.*t8.*t11,t2.*t5.*t7.*t8.*t11,t3.*t5.*t6.*t9.*t11,t3.*t5.*t7.*t9.*t11,t5.*t6.*t8.*t9.*t11,t5.*t7.*t8.*t9.*t11,t2.*t3.*t6.*t10.*t11,t2.*t3.*t7.*t10.*t11,t2.*t6.*t8.*t10.*t11,t2.*t7.*t8.*t10.*t11,t3.*t6.*t9.*t10.*t11,t3.*t7.*t9.*t10.*t11,t6.*t8.*t9.*t10.*t11,t7.*t8.*t9.*t10.*t11];
