function E3 = EPolar3(P_Sum,P_Vis,P_IR)
%EPOLAR3
%    E3 = EPOLAR3(O_PU1,O_SIG,O_VI)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Nov-2016 18:37:46

t2 = cos(P_Sum);
t3 = cos(P_Vis);
t4 = cos(P_IR);
t5 = sin(P_IR);
t6 = sin(P_Vis);
t7 = sin(P_Sum);
E3 = [t2.*t3.*t4,t2.*t3.*t5,t2.*t4.*t6,t2.*t5.*t6,t3.*t4.*t7,t3.*t5.*t7,t4.*t6.*t7,t5.*t6.*t7];
