function E4 = EPolar4(P_Signal,P_Probe,O_Pump2,O_Pump1)
%EPOLAR4
%    E4 = EPOLAR4(O_PR,O_PU1,O_PU2,O_SIG)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Nov-2016 18:37:46

t2 = cos(P_Probe);
t3 = cos(O_Pump2);
t4 = cos(P_Signal);
t5 = cos(O_Pump1);
t6 = sin(O_Pump1);
t7 = sin(O_Pump2);
t8 = sin(P_Probe);
t9 = sin(P_Signal);
E4 = [t2.*t3.*t4.*t5,t2.*t3.*t4.*t6,t2.*t4.*t5.*t7,t2.*t4.*t6.*t7,t3.*t4.*t5.*t8,t3.*t4.*t6.*t8,t4.*t5.*t7.*t8,t4.*t6.*t7.*t8,t2.*t3.*t5.*t9,t2.*t3.*t6.*t9,t2.*t5.*t7.*t9,t2.*t6.*t7.*t9,t3.*t5.*t8.*t9,t3.*t6.*t8.*t9,t5.*t7.*t8.*t9,t6.*t7.*t8.*t9];
