function E5 = EPolar5(O_Pr,O_Pu1,O_Pu2,O_Sig,O_Vi)
%EPOLAR5
%    E5 = EPOLAR5(O_PR,O_PU1,O_PU2,O_SIG,O_VI)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Nov-2016 18:37:46

t2 = cos(O_Pr);
t3 = cos(O_Pu2);
t4 = cos(O_Sig);
t5 = cos(O_Vi);
t6 = cos(O_Pu1);
t7 = sin(O_Pu1);
t8 = sin(O_Pu2);
t9 = sin(O_Pr);
t10 = sin(O_Vi);
t11 = sin(O_Sig);
E5 = [t2.*t3.*t4.*t5.*t6,t2.*t3.*t4.*t5.*t7,t2.*t4.*t5.*t6.*t8,t2.*t4.*t5.*t7.*t8,t3.*t4.*t5.*t6.*t9,t3.*t4.*t5.*t7.*t9,t4.*t5.*t6.*t8.*t9,t4.*t5.*t7.*t8.*t9,t2.*t3.*t4.*t6.*t10,t2.*t3.*t4.*t7.*t10,t2.*t4.*t6.*t8.*t10,t2.*t4.*t7.*t8.*t10,t3.*t4.*t6.*t9.*t10,t3.*t4.*t7.*t9.*t10,t4.*t6.*t8.*t9.*t10,t4.*t7.*t8.*t9.*t10,t2.*t3.*t5.*t6.*t11,t2.*t3.*t5.*t7.*t11,t2.*t5.*t6.*t8.*t11,t2.*t5.*t7.*t8.*t11,t3.*t5.*t6.*t9.*t11,t3.*t5.*t7.*t9.*t11,t5.*t6.*t8.*t9.*t11,t5.*t7.*t8.*t9.*t11,t2.*t3.*t6.*t10.*t11,t2.*t3.*t7.*t10.*t11,t2.*t6.*t8.*t10.*t11,t2.*t7.*t8.*t10.*t11,t3.*t6.*t9.*t10.*t11,t3.*t7.*t9.*t10.*t11,t6.*t8.*t9.*t10.*t11,t7.*t8.*t9.*t10.*t11];
