function GUI = GUI_Comb2(fig)
%% Ask for avalible models
[~,StructureModelList] = StructureModel(0,'List');
   
%% Add base layout
MainLayout = uix.HBoxFlex(...
    'Parent',fig,...
    'Spacing',1,...
    'Padding',5);

LeftPanel = uix.VBox( ...
    'Parent',MainLayout);

RightPanel = uix.VBox( ...
    'Parent',MainLayout);

% set sizes
set(MainLayout,'Widths',[-1,-1])
VBoxHight = [175,-1];

%% Left Panel

LeftPanelLayout = uix.VBox('Parent',LeftPanel,...
    'Padding', 3, 'Spacing', 3);

Struc1Panel = uix.BoxPanel( ...
    'Parent',LeftPanelLayout,...
    'Title','1st structure','FontSize',14);

ButtonBox = uix.VBox( ...
    'Parent',LeftPanelLayout);

set(LeftPanelLayout, 'Heights', VBoxHight ); % Make the list fill the space

%% Right Panel

RightPanelLayout = uix.VBox('Parent',RightPanel,...
    'Padding', 3, 'Spacing', 3);

Struc2Panel = uix.BoxPanel( ...
    'Parent',RightPanelLayout,...
    'Title','2nd Structure','FontSize',14);

RelativePositionPanel = uix.BoxPanel( ...
    'Parent',RightPanelLayout,...
    'Title','2nd structure','FontSize',14);

set(RightPanelLayout, 'Heights', VBoxHight ); % Make the list fill the space

%% Left Panel, Structure 1
Struc1Layout = uix.VBox('Parent',Struc1Panel,...
    'Padding', 3, 'Spacing', 3);

Struct1ListBox = uicontrol( 'Style', 'list', ...
   'BackgroundColor', 'w', ...
   'Parent', Struc1Layout, ...
   'String', StructureModelList(:), ...
   'fontunits', 'point', 'fontsize', 14,...
   'Value', 1,...
   'Tag','StructBox1');
Select1Button = uicontrol( 'Style', 'PushButton', ...
   'Parent', Struc1Layout, ...
   'String', 'Select Structure Model', ...
   'Callback', @(hObject,eventdata)Model_Comb2('Struc1',hObject,eventdata,guidata(hObject)));

set(Struc1Layout, 'Heights', [-1,28] ); % Make the list fill the space

%% Left Panel, Buttom
uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', 'Update Structure',...
    'fontunits', 'point', 'fontsize', 14,...
    'Callback',@(hObject,eventdata)Model_Comb2('UpdateStructure',hObject,eventdata,guidata(hObject)));

uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', 'Export Handle', ...
    'fontunits', 'point', 'fontsize', 14,...
    'Callback',@(hObject,eventdata)Model_Comb2('Export_Handle_Callback',hObject,eventdata,guidata(hObject)));

uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', 'Plot Molecule', ...
    'fontunits', 'point', 'fontsize', 14,...
    'Callback',@(hObject,eventdata)Model_Comb2('PlotComb2_Callback',hObject,eventdata,guidata(hObject)));


uix.Empty('Parent', ButtonBox)

set(ButtonBox,'Heights',[28,28,28,-1])

%% Right Panel, Structure 2
Struc2Layout = uix.VBox('Parent',Struc2Panel,...
    'Padding', 3, 'Spacing', 3);

Struct2ListBox = uicontrol( 'Style', 'list', ...
   'BackgroundColor', 'w', ...
   'Parent', Struc2Layout, ...
   'String', StructureModelList(:), ...
   'fontunits', 'point', 'fontsize', 14,...
   'Value', 1,...
   'Tag','StructBox2');
Select2Button = uicontrol( 'Style', 'PushButton', ...
   'Parent', Struc2Layout, ...
   'String', 'Select Structure Model', ...
   'Callback', @(hObject,eventdata)Model_Comb2('Struc2',hObject,eventdata,guidata(hObject)));
set(Struc2Layout, 'Heights', [-1,28] ); % Make the list fill the space

%% Right Panel, Relative orientation
RelativePositionLayout = uix.HBox('Parent',RelativePositionPanel,...
    'Padding', 3, 'Spacing', 3);

    VtextBox = uix.VBox('Parent',RelativePositionLayout,...
    'Padding', 3, 'Spacing', 3);
        uicontrol('Parent',VtextBox,...
        'Style','text',...
        'String','Ang/Deg',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',VtextBox,...
        'Style','text',...
        'String','Trans.',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

        uicontrol('Parent',VtextBox,...
        'Style','text',...
        'String','Rot.',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
    
    XBox = uix.VBox('Parent',RelativePositionLayout,...
    'Padding', 3, 'Spacing', 3);
        uicontrol('Parent',XBox,...
        'Style','text',...
        'String','X',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',XBox,...
        'Style','edit',...
        'String','0',...
        'Tag','Trans_X',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',XBox,...
        'Style','edit',...
        'String','0',...
        'Tag','Rot_Phi',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

    Vis_BeamBox1D = uix.VBox('Parent',RelativePositionLayout,...
    'Padding', 3, 'Spacing', 3);
        uicontrol('Parent',Vis_BeamBox1D,...
        'Style','text',...
        'String','Y',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Vis_BeamBox1D,...
        'Style','edit',...
        'String','0',...
        'Tag','Trans_Y',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Vis_BeamBox1D,...
        'Style','edit',...
        'String','0',...
        'Tag','Rot_Psi',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
    Sig_BeamBox1D = uix.VBox('Parent',RelativePositionLayout,...
    'Padding', 3, 'Spacing', 3);
        uicontrol('Parent',Sig_BeamBox1D,...
        'Style','text',...
        'String','Z',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Sig_BeamBox1D,...
        'Style','edit',...
        'String','4.75',...
        'Tag','Trans_Z',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Sig_BeamBox1D,...
        'Style','edit',...
        'String','0',...
        'Tag','Rot_Theta',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
set(RelativePositionLayout,'Widths',[-2,-1,-1,-1])

%% output handles
GUI = guihandles(fig);

