function hGUIs = GUI_COSMOSS(hCOSMOSS)
% This function will build all GUI elements on pre-build GUI base figure

%% Pre-setting
Version = '1.8.0';

%% Add base layout
MainLayout = uix.VBoxFlex(...
                         'Parent',hCOSMOSS,...
                         'Spacing',5,...
                         'Padding',1);
PanelLayout = uix.HBoxFlex(...
                           'Parent',MainLayout,...
                           'Spacing',5,...
                           'Padding',1);
LBox = uix.VBoxFlex(...
                    'Parent',PanelLayout,...
                    'Spacing',5,...
                    'Padding',1);
    % Creat panels on LBox
    StructurePanel = uix.BoxPanel(...
                                  'Parent',LBox,...
                                  'Title','Building Model Structure     ','FontSize',12);
    Beta_Panel = uix.BoxPanel(...
                              'Parent',LBox,...
                              'Title','H & Feynman-Path     ','FontSize',12);    
    RAvg_Panel = uix.BoxPanel(...
                              'Parent',LBox,...
                              'Title','Sample Symmetry     ','FontSize',12);    
    EJ_Panel = uix.BoxPanel(...
                            'Parent',LBox,...
                            'Title','Experiment Parameters     ','FontSize',12);    
    % Version number box
    uicontrol('Parent',LBox,...
              'Style','text',...
              'String',['COSMOSS Version: v', Version],...
              'HorizontalAlignment','center',...
              'units', 'normalized',...
              'fontunits', 'point', 'fontsize', 14);    
RBox = uix.VBoxFlex(...
                    'Parent',PanelLayout,...
                    'Spacing',5,...
                    'Padding',1);
    % Creat panels on RBox
    DisorderPanel = uix.BoxPanel(...
                                 'Parent',RBox,...
                                 'Title','Ensemble Average     ','FontSize',12);
    FigurePanel = uix.BoxPanel(...
                               'Parent',RBox,...
                               'Title','Figure Setting     ','FontSize',12);   
    AnalysisToolPanel = uix.BoxPanel(...
                                     'Parent',RBox,...
                                     'Title','Spectral Analysis Tools     ','FontSize',12);
ButtonBox = uix.HBoxFlex(...
                         'Parent', MainLayout,...
                         'Padding', 2);
% set sizes 
set(MainLayout ,'Heights',[-1,35])
set(PanelLayout,'Widths' ,[-1,-1])
set(LBox       ,'Heights',[-1,120,75,140,20])
set(RBox       ,'Heights',[140,235,-1])

%% Create buttons
uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', 'FTIR',...
    'Callback', @(hObject,eventdata)COSMOSS_Old('FTIR_Callback',hObject,eventdata,guidata(hObject)));
uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', 'SFG',...
    'Callback', @(hObject,eventdata)COSMOSS_Old('SFG_Callback',hObject,eventdata,guidata(hObject)));
uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', '2DIR',...
    'Callback', @(hObject,eventdata)COSMOSS_Old('TwoDIR_Callback',hObject,eventdata,guidata(hObject)));
uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', '2DSFG',...
    'Callback', @(hObject,eventdata)COSMOSS_Old('TwoDSFG_Callback',hObject,eventdata,guidata(hObject)));
uicontrol( 'Parent', ButtonBox, ...
    'enable','on',...
    'Style', 'PushButton', ...
    'String', 'AR SFG',...
    'Callback', @(hObject,eventdata)COSMOSS_Old('AR_SFG_Callback',hObject,eventdata,guidata(hObject))); 
uicontrol( 'Parent', ButtonBox, ...
    'Style', 'PushButton', ...
    'String', 'Export Handle', ...
    'Callback', @(hObject,eventdata)COSMOSS_Old('Export_Handle_Callback',hObject,eventdata,guidata(hObject)));

%% StructurePanel
% Ask for avalible models
[~,StructureModelList,~] = StructureModel(0);

StrucPanelLayout = uix.VBox('Parent', StructurePanel, ...
                            'Padding', 1, 'Spacing', 1 );
StructListBox = uicontrol('Style', 'list', ...
                          'BackgroundColor', 'w', ...
                          'Parent', StrucPanelLayout, ...
                          'String', StructureModelList(:), ...
                          'fontunits', 'point', 'fontsize', 14,...
                          'Value', 1,...
                          'Tag','StructListBox');
SelectButton = uicontrol('Style', 'PushButton', ...
                         'Parent', StrucPanelLayout, ...
                         'String', 'Select Structure Model', ...
                         'Callback', @(hObject,eventdata)COSMOSS_Old('onListSelection',hObject,eventdata,guidata(hObject)));
set(StrucPanelLayout,'Heights', [-1 28] ); % Make the list fill the space

%% Coupling / Signal panel (Beta)
[~,CouplingList] = Coupling('','List','');
LocFreqList = {'Same','Jansen Map'};

CSPanelLayout = uix.VBox('Parent',Beta_Panel,...
                         'Padding', 1, 'Spacing', 1);

    CSPanelHBox = uix.HBox('Parent',CSPanelLayout,...
                           'Padding', 1, 'Spacing', 1);
        CSTextBox = uix.VBox('Parent',CSPanelHBox,...
                             'Padding', 1, 'Spacing', 1);
            uicontrol('Parent',CSTextBox,...
                      'Style','text',...
                      'String','Local mode freq:',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
            uicontrol('Parent',CSTextBox,...
                      'Style','text',...
                      'String','Coupling Model:',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
            uicontrol('Parent',CSTextBox,...
                      'Style','text',...
                      'String','Beta NN (cm-1):',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);  
            uicontrol('Parent',CSTextBox,...
                      'Style','text',...
                      'String','Pathway Cut-Off: ',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);  
        CSEditBox = uix.VBox('Parent',CSPanelHBox,...
                             'Padding', 1, 'Spacing', 1);
            uicontrol('Parent',CSEditBox,...
                      'Style','popupmenu',...
                      'String',LocFreqList,...
                      'Value',1,...
                      'HorizontalAlignment','right',...
                      'Tag','LocFreqType',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
            uicontrol('Parent',CSEditBox,...
                      'Style','popupmenu',...
                      'String',CouplingList,...
                      'Value',1,...
                      'HorizontalAlignment','right',...
                      'Tag','CouplingModelIndex',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
            uicontrol('Parent',CSEditBox,...
                      'Style','edit',...
                      'String','0.8',...
                      'HorizontalAlignment','left',...
                      'Tag','Beta_NN',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
            uicontrol('Parent',CSEditBox,...
                      'Style','edit',...
                      'String','1e-5',...
                      'HorizontalAlignment','left',...
                      'Tag','PCutOff',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
    set(CSPanelHBox,'Widths',[-1,-1])

    uix.Empty('Parent',CSPanelLayout);
set(CSPanelLayout,'Heights',[95,-1])

%% Sample Symmetry (<R>)
SamplePanelLayout = uix.HBox('Parent',RAvg_Panel,...
    'Padding', 1, 'Spacing', 1);

    Sample_TextBox = uix.VBox('Parent',SamplePanelLayout);
        uicontrol('Parent',Sample_TextBox,...
        'Style','text',...
        'String','Rotational Avg:',...
        'HorizontalAlignment','right',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

        uicontrol('Parent',Sample_TextBox,...
        'Style','text',...
        'String','Mirror Plane:',...
        'HorizontalAlignment','right',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

    Sample_OptionBox = uix.VBox('Parent',SamplePanelLayout);
        uicontrol('Parent',Sample_OptionBox,...
        'Tag','Avg_Rot',...
        'Style','popupmenu',...
        'String',{'Phi','Psi','Phi,Psi','Isotropic','C1'},...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

        uicontrol('Parent',Sample_OptionBox,...
        'Tag','Avg_Mirror',...
        'Style','popupmenu',...
        'String',{'No','Sigma_v'},...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

set(SamplePanelLayout,'Widths',[130,-1])

%% Experimental Condition Panel(E,J)
LaserTabGP = uitabgroup('Parent',EJ_Panel,'Tag','LaserSetting');

OneDTab = uitab(LaserTabGP,'Title','1D','Tag','Tab_1D');

OneDTabLayout = uix.HBox('Parent',OneDTab,...
    'Padding', 1, 'Spacing', 1);

    VtextBox1D = uix.VBox('Parent',OneDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',VtextBox1D,...
        'Style','text',...
        'String','Unit Degrees',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',VtextBox1D,...
        'Style','text',...
        'String','Angles',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

        uicontrol('Parent',VtextBox1D,...
        'Style','text',...
        'String','Polarization',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
    
    IR_BeamBox1D = uix.VBox('Parent',OneDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',IR_BeamBox1D,...
        'Style','text',...
        'String','IR',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',IR_BeamBox1D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_IR',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',IR_BeamBox1D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_IR',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

    Vis_BeamBox1D = uix.VBox('Parent',OneDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Vis_BeamBox1D,...
        'Style','text',...
        'String','Vis',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Vis_BeamBox1D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Vis1D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Vis_BeamBox1D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Vis1D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
    Sig_BeamBox1D = uix.VBox('Parent',OneDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Sig_BeamBox1D,...
        'Style','text',...
        'String','Sig',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Sig_BeamBox1D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Sig1D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Sig_BeamBox1D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Sig1D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
set(OneDTabLayout,'Widths',[-2,-1,-1,-1])
    
TwoDTab = uitab(LaserTabGP,'Title','2D','Tag','Tab_2D');
TwoDTabFontSize = 12;
TwoDTabLayout = uix.HBox('Parent',TwoDTab,...
    'Padding', 1, 'Spacing', 1);

    VtextBox2D = uix.VBox('Parent',TwoDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',VtextBox2D,...
        'Style','text',...
        'String','Degrees',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',VtextBox2D,...
        'Style','text',...
        'String','Angles',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);

        uicontrol('Parent',VtextBox2D,...
        'Style','text',...
        'String','Polarization',...
        'HorizontalAlignment','left',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
    
    Pump1_BeamBox2D = uix.VBox('Parent',TwoDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Pump1_BeamBox2D,...
        'Style','text',...
        'String','Pu1',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Pump1_BeamBox2D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Pump1',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Pump1_BeamBox2D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Pump1',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
    Pump2_BeamBox2D = uix.VBox('Parent',TwoDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Pump2_BeamBox2D,...
        'Style','text',...
        'String','Pu2',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Pump2_BeamBox2D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Pump2',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Pump2_BeamBox2D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Pump2',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
    Probe_BeamBox2D = uix.VBox('Parent',TwoDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Probe_BeamBox2D,...
        'Style','text',...
        'String','Pr',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Probe_BeamBox2D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Probe',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Probe_BeamBox2D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Probe',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);

    Vis_BeamBox2D = uix.VBox('Parent',TwoDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Vis_BeamBox2D,...
        'Style','text',...
        'String','Vis',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Vis_BeamBox2D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Vis2D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Vis_BeamBox2D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Vis2D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
    Sig_BeamBox2D = uix.VBox('Parent',TwoDTabLayout,...
    'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',Sig_BeamBox2D,...
        'Style','text',...
        'String','Sig',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Sig_BeamBox2D,...
        'Style','edit',...
        'String','90',...
        'Tag','A_Sig2D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
        uicontrol('Parent',Sig_BeamBox2D,...
        'Style','edit',...
        'String','0',...
        'Tag','P_Sig2D',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', TwoDTabFontSize);
    
set(TwoDTabLayout,'Widths',[-2,-1,-1,-1,-1,-1])

%% Ensemble Average Panel                                           
DDPanelLayout = uix.VBox('Parent',DisorderPanel,...
    'Padding', 1, 'Spacing', 1);
    %% Diag Disorder toggle + # Sample                              
    NSampleHBox = uix.HBox('Parent',DDPanelLayout,...
                           'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',NSampleHBox,...
                  'Style','checkbox' ,...
                  'String','DD/ODD',...
                  'Tag','Sampling',...
                  'Value',0,...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',NSampleHBox,...
                  'Style','text',...
                  'String',', Sample#:',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);    
        uicontrol('Parent',NSampleHBox,...
                  'Style','edit',...
                  'String','1',...
                  'HorizontalAlignment','right',...
                  'Tag','Sample_Num',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(NSampleHBox,'Widths',[80,80,-1])
    %% Dynamic fig update + Continue toggle                         
    ToggleHBox = uix.HBox('Parent',DDPanelLayout,...
                      'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',ToggleHBox,...
                'Style','checkbox' ,...
                'String','Dynamic fig. update',...
                'Tag','DynamicUpdate',...
                'Value',0,...
                'units', 'normalized',...
                'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',ToggleHBox,...
                'Style','checkbox' ,...
                'String','Continue?',...
                'Tag','UpdateStatus',...
                'Value',1,...
                'units', 'normalized',...
                'fontunits', 'point', 'fontsize', 14);
    set(ToggleHBox,'Widths',[160,-1])
    %% Fluctuation Corelation                                     
    DDHBox = uix.HBox('Parent',DDPanelLayout,...
                      'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',DDHBox,...
                  'Style','text',...
                  'String','Fluctuation Correlation (%)',...
                  'HorizontalAlignment','Right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',DDHBox,...
                  'Style','edit',...
                  'String','0',...
                  'HorizontalAlignment','right',...
                  'Tag','P_FlucCorr',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(DDHBox,'Widths',[220,-1])
    %% Diagonal disorder FWHM                                       
    DDFreqHBox = uix.HBox('Parent',DDPanelLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol('Parent',DDFreqHBox,...
                  'Style','text',...
                  'String','Digonal disorder FWHM (cm-1)',...
                  'HorizontalAlignment','Right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',DDFreqHBox,...
                  'Style','edit',...
                  'String','10',...
                  'HorizontalAlignment','Right',...
                  'Tag','DD_FWHM',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(DDFreqHBox,'Widths',[220,-1])
    %% Off-Diagonal disorder FWHM                                       
    ODDFreqHBox = uix.HBox('Parent',DDPanelLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol('Parent',ODDFreqHBox,...
                  'Style','text',...
                  'String','Off-digonal disorder FWHM (cm-1)',...
                  'HorizontalAlignment','Right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',ODDFreqHBox,...
                  'Style','edit',...
                  'String','0',...
                  'HorizontalAlignment','Right',...
                  'Tag','ODD_FWHM',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(ODDFreqHBox,'Widths',[220,-1])
set(DDPanelLayout,'Heights',[-1,-1,-1,-1,-1])

%% Figure Setting panel                                             

FPanelLayout = uix.VBox('Parent',FigurePanel,...
    'Padding', 1, 'Spacing', 1);
    %% Figure Saving                                                
    CheckBoxRaw1 = uix.HBox('Parent',FPanelLayout,...
                            'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',CheckBoxRaw1,...
                  'Style','checkbox' ,...
                  'String','Save Fig to ',...
                  'Tag','SaveFig',...
                  'Value',0,...
                  'units', 'normalized',...
                  'Callback', @(hObject,eventdata)COSMOSS_Old('Toggle_Fig_Save_Callback',hObject,eventdata,guidata(hObject)),...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',CheckBoxRaw1,...
                  'Style','edit',...
                  'String','~/Desktop/TMP',...
                  'HorizontalAlignment','left',...
                  'Tag','SavePath',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(CheckBoxRaw1,'Widths',[100,-1])
    %% CheckBox                                                     
    CheckBoxRaw2 = uix.HBox('Parent',FPanelLayout,...
                            'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',CheckBoxRaw2,...
                  'Style','checkbox' ,...
                  'String','Stick',...
                  'Tag','PlotStick',...
                  'Value',1,...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',CheckBoxRaw2,...
                  'Style','checkbox' ,...
                  'String','Normalize',...
                  'Tag','PlotNorm',...
                  'Value',0,...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',CheckBoxRaw2,...
                  'Style','checkbox' ,...
                  'String','Cursor',...
                  'Tag','PlotCursor',...
                  'Value',0,...
                  'units', 'normalized',...
                  'Callback', @(hObject,eventdata)COSMOSS_Old('Toggle_Fig_DataCursor_Callback',hObject,eventdata,guidata(hObject)),...
                  'fontunits', 'point', 'fontsize', 14);
    set(CheckBoxRaw2,'Widths',[70,100,-1])
    %% FRrangeHBox                                                  
    FRrangeHBox = uix.HBox('Parent',FPanelLayout,...
        'Padding', 1, 'Spacing', 1);
            uicontrol('Parent',FRrangeHBox,...
            'Style','text',...
            'String','Freq. Min:',...
            'HorizontalAlignment','right',...
            'units', 'normalized',...
            'fontunits', 'point', 'fontsize', 14);
        
            uicontrol('Parent',FRrangeHBox,...
            'Style','edit',...
            'String','1650',...
            'HorizontalAlignment','right',...
            'Tag','F_Min',...
            'units', 'normalized',...
            'fontunits', 'point', 'fontsize', 14);
        
            uicontrol('Parent',FRrangeHBox,...
            'Style','text',...
            'String',', Max:',...
            'HorizontalAlignment','right',...
            'units', 'normalized',...
            'fontunits', 'point', 'fontsize', 14);
     
            uicontrol('Parent',FRrangeHBox,...
            'Style','edit',...
            'String','1750',...
            'HorizontalAlignment','right',...
            'Tag','F_Max',...
            'units', 'normalized',...
            'fontunits', 'point', 'fontsize', 14);

            uicontrol('Parent',FRrangeHBox,...
            'Style','text',...
            'String','cm-1',...
            'HorizontalAlignment','right',...
            'units', 'normalized',...
            'fontunits', 'point', 'fontsize', 14);        
    set(FRrangeHBox,'Widths',[70,-1,50,-1,40]) 
    %% Homogenoeous lineshape Box                                   
    LineshapeHBox = uix.HBox('Parent',FPanelLayout,...
                             'Padding', 1, 'Spacing', 1);
        uicontrol('Parent',LineshapeHBox,...
                  'Style','text',...
                  'String','LineShape:',...
                  'HorizontalAlignment','right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',LineshapeHBox,...
                  'Style','popupmenu',...
                  'String',{'Gaussian','Lorentizan','K-K','None','Spy'},...
                  'Value',2,...
                  'HorizontalAlignment','right',...
                  'Tag','LineShape',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',LineshapeHBox,...
                  'Style','text',...
                  'String','W:',...
                  'HorizontalAlignment','right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',LineshapeHBox,...
                  'Style','edit',...
                  'String','5',...
                  'HorizontalAlignment','right',...
                  'Tag','LineWidth',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
          uicontrol('Parent',LineshapeHBox,...
                  'Style','text',...
                  'String','cm-1',...
                  'HorizontalAlignment','right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
    set(LineshapeHBox,'Widths',[70,110,20,-1,40])    
    %% Contour Box                                                  
    ContourHBox = uix.HBox('Parent',FPanelLayout,...
                           'Padding', 1, 'Spacing', 1);    
        uicontrol('Parent',ContourHBox,...
                  'Style','text',...
                  'String','#Contours: ',...
                  'HorizontalAlignment','right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14); 
        uicontrol('Parent',ContourHBox,...
                  'Style','edit',...
                  'String','20',...
                  'HorizontalAlignment','right',...
                  'Tag','Num_Contour',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',ContourHBox,...
                  'Style','text',...
                  'String',', Colormap: ',...
                  'HorizontalAlignment','right',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        [~,CMap_List] = SelectColormap('List');
        uicontrol('Parent',ContourHBox,...
                  'Style','popupmenu',...
                  'String',CMap_List,...
                  'Value',1,...
                  'HorizontalAlignment','right',...
                  'Tag','CMAP_Index',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);    
      set(ContourHBox,'Widths',[70,30,80,-1])            
    %% TwoD related options                                         
    TwoDHBoxLayout = uix.HBox('Parent',FPanelLayout,...
                              'Padding', 1, 'Spacing', 1);
        TwoDTextVBox = uix.VBox('Parent',TwoDHBoxLayout,...
                                'Padding', 1, 'Spacing', 1);
            uicontrol('Parent',TwoDTextVBox,...
                      'Style','text',...
                      'String','Signal Type:',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);

            uicontrol('Parent',TwoDTextVBox,...
                      'Style','text',...
                      'String','Spectrum Type:',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);

            uicontrol('Parent',TwoDTextVBox,...
                      'Style','text',...
                      'String','Pathway:',...
                      'HorizontalAlignment','right',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
        TwoDEditVBox = uix.VBox('Parent',TwoDHBoxLayout,...
                                'Padding', 1, 'Spacing', 1);
            uicontrol('Parent',TwoDEditVBox,...
                      'Style','popupmenu',...
                      'String',{'Heterodyne','Homodyne'},...
                      'HorizontalAlignment','right',...
                      'Tag','Signal_Type',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);

            uicontrol('Parent',TwoDEditVBox,...
                      'Style','popupmenu',...
                      'String',{'Absorptive','Rephasing','Non-rephasing'},...
                      'HorizontalAlignment','right',...
                      'Tag','SpecType',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);

            uicontrol('Parent',TwoDEditVBox,...
                      'Style','popupmenu',...
                      'String',{'All','GB','SE','EA'},...
                      'HorizontalAlignment','right',...
                      'Tag','Pathway',...
                      'units', 'normalized',...
                      'fontunits', 'point', 'fontsize', 14);
    
set(FPanelLayout,'Heights',[25,25,25,25,25,-1])

%% Analysis Tool tab groups
AnalysisToolsTabGP = uitabgroup('Parent',AnalysisToolPanel,'Tag','AnalysisTools');

% FTIR
FTIR_Tab = uitab(AnalysisToolsTabGP,'Title','FTIR','Tag','Tab_FTIR');
FTIR_TabLayout = uix.HBox('Parent',FTIR_Tab,...
    'Padding', 1, 'Spacing', 1);

% SFG
SFG_Tab = uitab(AnalysisToolsTabGP,'Title','SFG','Tag','Tab_FTIR');
SFG_TabLayout = uix.HBox('Parent',SFG_Tab,...
    'Padding', 1, 'Spacing', 1);

    uicontrol('Parent',SFG_TabLayout,...
              'Style','checkbox' ,...
              'String','Integral Area for SFG',...
              'Tag','IntegralArea',...
              'Value',0,...
              'units', 'normalized',...
              'fontunits', 'point', 'fontsize', 14);

% 2DIR
TwoDIR_Tab = uitab(AnalysisToolsTabGP,'Title','2DIR','Tag','Tab_FTIR');
TwoDIR_TabLayout = uix.VBox('Parent',TwoDIR_Tab,...
    'Padding', 1, 'Spacing', 1);
    HCut_2DIR_HBox = uix.HBox('Parent',TwoDIR_TabLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol( 'Parent', HCut_2DIR_HBox, ...
            'Style', 'PushButton', ...
            'String', 'Horizontal cut @:',...
            'fontunits', 'point', 'fontsize', 14,...
            'Callback', @(hObject,eventdata)COSMOSS_Old('HCut_Callback',hObject,eventdata,guidata(hObject)));
        uicontrol('Parent',HCut_2DIR_HBox,...
                    'Style','edit',...
                    'String','0',...
                    'HorizontalAlignment','right',...
                    'Tag','HCut_2DIR',...
                    'units', 'normalized',...
                    'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',HCut_2DIR_HBox,...
                    'Style','text',...
                    'String','cm-1',...
                    'HorizontalAlignment','left',...
                    'units', 'normalized',...
                    'fontunits', 'point', 'fontsize', 14);
    set(HCut_2DIR_HBox,'Widths',[130,-1,40])   
        
    DiagCut_2DIR_HBox = uix.HBox('Parent',TwoDIR_TabLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol( 'Parent', DiagCut_2DIR_HBox, ...
            'Style', 'PushButton', ...
            'String', 'Diagonal cut',...
            'fontunits', 'point', 'fontsize', 14,...
            'Callback', @(hObject,eventdata)COSMOSS_Old('DiagCut_Callback',hObject,eventdata,guidata(hObject)));
        uix.Empty('Parent',DiagCut_2DIR_HBox);
    set(DiagCut_2DIR_HBox,'Widths',[130,-1])   
    
    TransitionStrength_2DIR_HBox = uix.HBox('Parent',TwoDIR_TabLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol( 'Parent', TransitionStrength_2DIR_HBox, ...
            'Style', 'PushButton', ...
            'String', 'Transitions',...
            'fontunits', 'point', 'fontsize', 14,...
            'Callback', @(hObject,eventdata)COSMOSS_Old('TransitionStrength_Callback',hObject,eventdata,guidata(hObject)));
        uix.Empty('Parent',TransitionStrength_2DIR_HBox);
    set(TransitionStrength_2DIR_HBox,'Widths',[130,-1])   

    uix.Empty('Parent',TwoDIR_TabLayout);
set(TwoDIR_TabLayout,'Heights',[30,30,30,-1])

% 2DSFG
TwoDSFG_Tab = uitab(AnalysisToolsTabGP,'Title','2DSFG','Tag','Tab_FTIR');
TwoDSFG_TabLayout = uix.VBox('Parent',TwoDSFG_Tab,...
    'Padding', 1, 'Spacing', 1);
    HCut_2DSFG_HBox = uix.HBox('Parent',TwoDSFG_TabLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol( 'Parent', HCut_2DSFG_HBox, ...
            'Style', 'PushButton', ...
            'String', 'Horizontal cut @:',...
            'fontunits', 'point', 'fontsize', 14,...
            'Callback', @(hObject,eventdata)COSMOSS_Old('HCut_Callback',hObject,eventdata,guidata(hObject)));
        uicontrol('Parent',HCut_2DSFG_HBox,...
                    'Style','edit',...
                    'String','0',...
                    'HorizontalAlignment','right',...
                    'Tag','HCut_2DSFG',...
                    'units', 'normalized',...
                    'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',HCut_2DSFG_HBox,...
                    'Style','text',...
                    'String','cm-1',...
                    'HorizontalAlignment','left',...
                    'units', 'normalized',...
                    'fontunits', 'point', 'fontsize', 14);
    set(HCut_2DSFG_HBox,'Widths',[130,-1,40])   
    
    DiagCut_2DSFG_HBox = uix.HBox('Parent',TwoDSFG_TabLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol( 'Parent', DiagCut_2DSFG_HBox, ...
            'Style', 'PushButton', ...
            'String', 'Diagonal cut',...
            'fontunits', 'point', 'fontsize', 14,...
            'Callback', @(hObject,eventdata)COSMOSS_Old('DiagCut_Callback',hObject,eventdata,guidata(hObject)));
        uix.Empty('Parent',DiagCut_2DSFG_HBox);
    set(DiagCut_2DSFG_HBox,'Widths',[130,-1])   
    
    TransitionStrength_2DSFG_HBox = uix.HBox('Parent',TwoDSFG_TabLayout,...
                          'Padding', 1, 'Spacing', 1);    
        uicontrol( 'Parent', TransitionStrength_2DSFG_HBox, ...
            'Style', 'PushButton', ...
            'String', 'Transitions',...
            'fontunits', 'point', 'fontsize', 14,...
            'Callback', @(hObject,eventdata)COSMOSS_Old('TransitionStrength_Callback',hObject,eventdata,guidata(hObject)));
        uicontrol('Parent',TransitionStrength_2DSFG_HBox,...
                  'Style','popupmenu',...
                  'String',{'Mu','Alpha'},...
                  'HorizontalAlignment','right',...
                  'Tag','TS_Type',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);

    set(TransitionStrength_2DSFG_HBox,'Widths',[130,-1])   
    

    uix.Empty('Parent',TwoDSFG_TabLayout);
set(TwoDSFG_TabLayout,'Heights',[30,30,30,-1])

%% output handles
hGUIs = guihandles(hCOSMOSS);

%% Add Properties Change Listner
FN_MiSC = {...
    'hMain',...
    'AnalysisTools',...
    'LaserSetting',...
    'Tab_FTIR',...
    'Tab_1D',...
    'Tab_2D',...
    'empty',...
    'StructListBox',...
    'DynamicUpdate',... 
    };

FN_FigureSetting = {...
    'SaveFig',...
    'SavePath',...
    'Num_Contour',...
    'PlotStick',...
    'PlotNorm',...
    'PlotCursor',...
    'CMAP_Index',...
    'F_Min',...
    'F_Max',...
    'LineShape',...
    'LineWidth',...
    'SpecType',...
    'Signal_Type',...
    'Pathway',...
};

FN_AnalysisTools = {...
    'IntegralArea',...
    'HCut_2DIR',...
    'HCut_2DSFG',...
};

S = hGUIs;
S = rmfield(S,FN_MiSC);
S = rmfield(S,FN_FigureSetting);
S = rmfield(S,FN_AnalysisTools);
SA = struct2array(S);

hL_Str = addlistener(SA,'String','PostSet',@(SA,eventdata)COSMOSS_Old('UpdateCalculation',SA,eventdata,guidata(hCOSMOSS)));
hL_Val = addlistener(SA, 'Value','PostSet',@(SA,eventdata)COSMOSS_Old('UpdateCalculation',SA,eventdata,guidata(hCOSMOSS)));

hGUIs.StringListner = hL_Str;
hGUIs.ValueListner = hL_Val;