function E4 = EPolar4(O_Sum,O_Probe,O_Pump2,O_Pump1)
%EPOLAR4
%    E4 = EPOLAR4(O_PUMP1,O_PUMP2,O_PROBE,O_SUM)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    09-Dec-2013 08:59:42

t2 = cos(O_Pump2);
t3 = cos(O_Probe);
t4 = cos(O_Sum);
t5 = cos(O_Pump1);
t6 = sin(O_Pump1);
t7 = sin(O_Pump2);
t8 = sin(O_Probe);
t9 = sin(O_Sum);
E4 = [t2.*t3.*t4.*t5,t2.*t3.*t4.*t6,t3.*t4.*t5.*t7,t3.*t4.*t6.*t7,t2.*t4.*t5.*t8,t2.*t4.*t6.*t8,t4.*t5.*t7.*t8,t4.*t6.*t7.*t8,t2.*t3.*t5.*t9,t2.*t3.*t6.*t9,t3.*t5.*t7.*t9,t3.*t6.*t7.*t9,t2.*t5.*t8.*t9,t2.*t6.*t8.*t9,t5.*t7.*t8.*t9,t6.*t7.*t8.*t9];
