function R1_ZYZ_2 = R1_ZYZ_2(Phi,Theta)
%R1_ZYZ_2
%    R1_ZYZ_2 = R1_ZYZ_2(PHI,THETA)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    08-Nov-2014 13:24:16

t2 = sin(Theta);
R1_ZYZ_2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t2.*cos(Phi),t2.*sin(Phi),cos(Theta)],[3, 3]);
