function [CMAP,CMap_List] = SelectColormap(map_Index)
    
CMap_List = {'Jet',...
             'JetWhite',...
             'JetBlack',...
             'JetWhiteWide',...
             'Jet_Pale',...
             'CoolBlack',...
             'CoolWhite',...
             'Jet_Reverse'};

%ColormapName = CMap_List{map_Index};
switch map_Index
    case 'List'
        % doing nothing for list inquary
        CMAP = [];
    case 'Jet'
        CMAP = colormap(CMap_List{map_Index});
    otherwise
        CMAP_tmp = load(CMap_List{map_Index});
        CMAP = CMAP_tmp.MAP;
end