function [CMAP,CMap_List] = SelectColormap(map)
    
CMap_List = {'Jet',...
             'JetWhite',...
             'JetBlackWide',...
             'JetBlack',...
             'JetWhiteWide',...
             'Jet_Pale',...
             'CoolBlack',...
             'CoolWhite',...
             'Jet_Reverse',...
             'Sign'};

%ColormapName = CMap_List{map_Index};
switch map
    case 'List'
        % doing nothing for list inquary
        CMAP = [];
    case 'Jet'
        CMAP = colormap('Jet');
    otherwise
        CMAP_tmp = load(map);
        CMAP = CMAP_tmp.MAP;
end