function GUI = GUI_PDB_AmideI(fig) 
%% Pre-setting
Version = '1.0.1';

%% Add base layout
MainLayout = uix.VBoxFlex(...
    'Parent',fig,...
    'Spacing',1,...
    'Padding',5);

MoleculePanel = uix.BoxPanel( ...
    'Parent',MainLayout,...
    'Title','Molecule Orientation','FontSize',14);

LabelPanel = uix.BoxPanel( ...
    'Parent',MainLayout,...
    'Title','Local Mode Frequency','FontSize',14);

FigurePanel = uix.BoxPanel( ...
    'Parent',MainLayout,...
    'Title','Molecule figure options','FontSize',14);

ButtonBox = uix.VBoxFlex( ...
    'Parent', MainLayout,...
    'Padding', 2);

set(MainLayout,'Height',[80,120,80,-1])

%% MoleculePanel 
MoleculePanelLayout = uix.VBoxFlex('Parent',MoleculePanel,...
    'Padding', 5, 'Spacing', 5);

    uicontrol('Parent',MoleculePanelLayout,...
        'Style','text',...
        'Tag','PDB_Name',...
        'String','PDB not loaded...');

    Rot_HBox = uix.HBoxFlex(...
        'Parent',MoleculePanelLayout,...
        'Spacing',3);

        uicontrol('Parent',Rot_HBox,...
            'Style','text',...
            'String','Phi');

        uicontrol('Parent',Rot_HBox,...
            'Style','edit',...
            'String','0',...
            'Tag','Phi_D',...
            'Callback',@(hObject,eventdata)Model_PDB_AmideI('UpdateStructure',hObject,eventdata,guidata(hObject)));

        uicontrol('Parent',Rot_HBox,...
            'Style','text',...
            'String','Psi');

        uicontrol('Parent',Rot_HBox,...
            'Style','edit',...
            'String','0',...
            'Tag','Psi_D',...
            'Callback',@(hObject,eventdata)Model_PDB_AmideI('UpdateStructure',hObject,eventdata,guidata(hObject)));

        uicontrol('Parent',Rot_HBox,...
            'Style','text',...
            'String','Theta');

        uicontrol('Parent',Rot_HBox,...
            'Style','edit',...
            'String','0',...
            'Tag','Theta_D',...
            'Callback',@(hObject,eventdata)Model_PDB_AmideI('UpdateStructure',hObject,eventdata,guidata(hObject)));
    
set(MoleculePanelLayout,'Height',[20,-1])

%% Labeling panel
LabelPanelLayout = uix.HBoxFlex('Parent',LabelPanel,...
    'Padding', 5, 'Spacing', 5);

    Freq_TextBox = uix.VBox('Parent',LabelPanelLayout);
        uicontrol('Parent',Freq_TextBox,...
        'Style','text',...
        'String','Non-Labeled Freq:',...
        'HorizontalAlignment','right',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Freq_TextBox,...
        'Style','text',...
        'String','Labeled Freq:',...
        'HorizontalAlignment','right',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Freq_TextBox,...
        'Style','text',...
        'String','Anharmonicty:',...
        'HorizontalAlignment','right',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Freq_TextBox,...
        'Style','text',...
        'String','Index of modes:',...
        'HorizontalAlignment','right',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
    

    Freq_EditBox = uix.VBox('Parent',LabelPanelLayout);
        uicontrol('Parent',Freq_EditBox,...
        'Style','edit',...
        'String','1645',...
        'Tag','NLFreq',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Freq_EditBox,...
        'Style','edit',...
        'String','1604',...
        'Tag','LFreq',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);
    
        uicontrol('Parent',Freq_EditBox,...
        'Style','edit',...
        'String','20',...
        'Tag','Anharm',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);   
        
        uicontrol('Parent',Freq_EditBox,...
        'Style','edit',...
        'String','None',...
        'Tag','L_Index',...
        'units', 'normalized',...
        'fontunits', 'point', 'fontsize', 14);

set(LabelPanelLayout,'Widths',[140,-1])

%% Plot molecule options
FigurePanelLayout = uix.VBox('Parent',FigurePanel,...
    'Padding', 5, 'Spacing', 5);

    FigureOptionLayout1 = uix.HBox('Parent',FigurePanelLayout,...
        'Padding', 5, 'Spacing', 5);    
        uicontrol('Parent',FigureOptionLayout1,...
                  'Style','checkbox',...
                  'String','Atoms,',...
                  'Value',1,...
                  'Tag','Plot_Atoms',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);     
        uicontrol('Parent',FigureOptionLayout1,...
                  'Style','checkbox',...
                  'String','Axis.',...
                  'Value',1,...
                  'Tag','Plot_Axis',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uix.Empty('Parent',FigureOptionLayout1);
    set(FigureOptionLayout1,'Widths',[80,80,-1])
    
    FigureOptionLayout2 = uix.HBox('Parent',FigurePanelLayout,...
        'Padding', 5, 'Spacing', 5);   
        uicontrol('Parent',FigureOptionLayout2,...
                  'Style','checkbox',...
                  'String','Bonds,',...
                  'Value',1,...
                  'Tag','Plot_Bonds',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);
        uicontrol('Parent',FigureOptionLayout2,...
                  'Style','checkbox',...
                  'String','SideChain.',...
                  'Value',0,...
                  'Tag','Plot_SideChain',...
                  'HorizontalAlignment','left',...
                  'units', 'normalized',...
                  'fontunits', 'point', 'fontsize', 14);  
      uix.Empty('Parent',FigureOptionLayout2);
      set(FigureOptionLayout2,'Widths',[80,120,-1])
      
set(FigurePanelLayout,'Heights',[-1,-1])

%% Button
uicontrol( 'Parent', ButtonBox, ...
'String', 'Load PDB',...
'Callback',@(hObject,eventdata)Model_PDB_AmideI('LoadStructure',hObject,eventdata,guidata(hObject)));

uicontrol( 'Parent', ButtonBox, ...
'String', 'Generate',...
'Callback',@(hObject,eventdata)Model_PDB_AmideI('UpdateStructure',hObject,eventdata,guidata(hObject)));

uicontrol( 'Parent', ButtonBox, ...
'String', 'Plot Molecule',...
'Callback',@(hObject,eventdata)Model_PDB_AmideI('PlotMolecule',hObject,eventdata,guidata(hObject)));

uicontrol( 'Parent', ButtonBox, ...
'String', 'Plot Modes',...
'Callback',@(hObject,eventdata)Model_PDB_AmideI('PlotModes',hObject,eventdata,guidata(hObject)));

uicontrol( 'Parent', ButtonBox, ...
'String', 'Export Handle',...
'Callback',@(hObject,eventdata)Model_PDB_AmideI('Export_Handle_Callback',hObject,eventdata,guidata(hObject)));

uicontrol('Parent',ButtonBox,...
          'Style','text',...
          'String',['Model Version: v',Version],...
          'HorizontalAlignment','Center',...
          'units', 'normalized',...
          'fontunits', 'point', 'fontsize', 14);       

set(ButtonBox,'Height',[-1,-1,-1,-1,-1,20])

%% output handles
GUI = guihandles(fig);
    