function hF = PlotXYZfiles_AmideI(Structure,GUI_Inputs)
%% PlotXYZfiles
%  
% Given the Stuctural infomation that generated by GetAmideI.m this
% function can plot the molecule and its' amide I modes.
% 
% ------- Version log -----------------------------------------------------
% 
% Ver. 1.4  140605  Readuce the process for reading XYZ data
% 
% Ver. 1.3  131107  Add imput "Rot_Mat" to rotate molecue as user assigned
%                   This is the correction follow by v1.2 of
%                   OneDSFG_AmideI.m
% 
% Ver. 1.2  130930  Move gplot3 from Molecular_Plot to here to accomodate
%                   the update of molecular_plot
% 
% Ver. 1.1  130814  Bug in atom position index fixed 
% 
% Ver. 1.0  130729  Isolated from TwoDSFG_Simulation
% 
% ------------------------------------------------------------------------
% Copyright Jia-Jung Ho, 2013

%% Debug

% PDB_Data    = ConstructGrid('Debug');
% PDB_Data = TwoMolConstruct;
% Orientation = [0,0,0];

%% Input parser
GUI_Inputs_C      = fieldnames(GUI_Inputs);
GUI_Inputs_C(:,2) = struct2cell(GUI_Inputs);
GUI_Inputs_C      = GUI_Inputs_C';

INPUT = inputParser;
INPUT.KeepUnmatched = 1;

% Default values
defaultAvg_Phi    = 0;
defaultAvg_Theta  = 0;
defaultAvg_Psi    = 0;
defaultPlot_Atoms = 1;
defaultPlot_Bonds = 1;
defaultPlot_Axis  = 1;

% Add optional inputs to inputparser object
addOptional(INPUT,'Avg_Phi'   ,defaultAvg_Phi);
addOptional(INPUT,'Avg_Theta' ,defaultAvg_Theta);
addOptional(INPUT,'Avg_Psi'   ,defaultAvg_Psi);
addOptional(INPUT,'Plot_Atoms',defaultPlot_Atoms);
addOptional(INPUT,'Plot_Bonds',defaultPlot_Bonds);
addOptional(INPUT,'Plot_Axis' ,defaultPlot_Axis);

parse(INPUT,GUI_Inputs_C{:});

Avg_Phi    = INPUT.Results.Avg_Phi;
Avg_Theta  = INPUT.Results.Avg_Theta;
Avg_Psi    = INPUT.Results.Avg_Psi;
Plot_Atoms = INPUT.Results.Plot_Atoms;
Plot_Bonds = INPUT.Results.Plot_Bonds;
Plot_Axis  = INPUT.Results.Plot_Axis;

%% Main
XYZ_MF    = Structure.XYZ;
Center_MF = Structure.center;

% Orientation = Orientation/180*pi; % turn to radius unit
Avg_Phi_R   =   Avg_Phi/180*pi;
Avg_Psi_R   =   Avg_Psi/180*pi;
Avg_Theta_R = Avg_Theta/180*pi;

R_MF_LF = R1_ZYZ_0(Avg_Phi_R,Avg_Psi_R,Avg_Theta_R);

XYZ_LF    = (R_MF_LF*XYZ_MF')';
Center_LF = (R_MF_LF*Center_MF')';

%% Position info
Carbon_Pos   = XYZ_LF(Structure.AtomSerNo(:,1),:);
Oxygen_Pos   = XYZ_LF(Structure.AtomSerNo(:,2),:);
Nitrogen_Pos = XYZ_LF(Structure.AtomSerNo(:,3),:);

hF = figure; 
hold on

    %% draw bonds
    if Plot_Bonds
        Conn = Connectivity(XYZ_LF);
        gplot3(Conn,XYZ_LF);
    end
    
    %% Draw atoms
    if Plot_Atoms
        plot3(Center_LF(:,1)  ,Center_LF(:,2)  ,Center_LF(:,3)  ,'LineStyle','none','Marker','d','MarkerFaceColor','w')
        plot3(Carbon_Pos(:,1)  ,Carbon_Pos(:,2)  ,Carbon_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','k','MarkerSize',10)
        plot3(Oxygen_Pos(:,1)  ,Oxygen_Pos(:,2)  ,Oxygen_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','r','MarkerSize',10)
        plot3(Nitrogen_Pos(:,1),Nitrogen_Pos(:,2),Nitrogen_Pos(:,3),'LineStyle','none','Marker','o','MarkerFaceColor','b','MarkerSize',10)
    end
    
    %% Draw molecular and Lab frame
    if Plot_Axis
        hAx = findobj(hF,'type','axes');
        Lab_Frame = [1,0,0;
                     0,1,0;
                     0,0,1 ];
                 
        Box_Cornor = [hAx.XLim(1),hAx.YLim(1),hAx.ZLim(1)];
        Box_length = [hAx.XLim(2),hAx.YLim(2),hAx.ZLim(2)] - [hAx.XLim(1),hAx.YLim(1),hAx.ZLim(1)];
        COA = Box_Cornor + (0.1).*Box_length;
        
        PlotRotMolFrame(hAx,Lab_Frame,R_MF_LF,COA)
    end

    %% Draw labeled atoms
    Plot_Label = 1;
    if Plot_Label
        L_Index = GUI_Inputs.L_Index;
        plot3(Carbon_Pos(L_Index,1)  ,Carbon_Pos(L_Index,2)  ,Carbon_Pos(L_Index,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','g','MarkerSize',11)
        plot3(Oxygen_Pos(L_Index,1)  ,Oxygen_Pos(L_Index,2)  ,Oxygen_Pos(L_Index,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','g','MarkerSize',11)
        plot3(Nitrogen_Pos(L_Index,1),Nitrogen_Pos(L_Index,2),Nitrogen_Pos(L_Index,3),'LineStyle','none','Marker','o','MarkerFaceColor','g','MarkerSize',11)

    end
    
hold off    
    
%% figure setting
xlabel('X')
ylabel('Y')
axis image;
rotate3d on