function hF = PlotXYZfiles_AmideI(PDB_Data,GUI_Inputs)
%% PlotXYZfiles
%  
% Given the Stuctural infomation that generated by GetAmideI.m this
% function can plot the molecule and its' amide I modes.
% 
% ------- Version log -----------------------------------------------------
% 
% Ver. 1.4  140605  Readuce the process for reading XYZ data
% 
% Ver. 1.3  131107  Add imput "Rot_Mat" to rotate molecue as user assigned
%                   This is the correction follow by v1.2 of
%                   OneDSFG_AmideI.m
% 
% Ver. 1.2  130930  Move gplot3 from Molecular_Plot to here to accomodate
%                   the update of molecular_plot
% 
% Ver. 1.1  130814  Bug in atom position index fixed 
% 
% Ver. 1.0  130729  Isolated from TwoDSFG_Simulation
% 
% ------------------------------------------------------------------------
% Copyright Jia-Jung Ho, 2013

%% Debug

% PDB_Data    = ConstructGrid('Debug');
% PDB_Data = TwoMolConstruct;
% Orientation = [0,0,0];

%% Input parser
GUI_Inputs_C      = fieldnames(GUI_Inputs);
GUI_Inputs_C(:,2) = struct2cell(GUI_Inputs);
GUI_Inputs_C      = GUI_Inputs_C';

INPUT = inputParser;
INPUT.KeepUnmatched = 1;

% Default values
defaultPlot_Atoms = 1;
defaultPlot_Bonds = 1;

% Add optional inputs to inputparser object
addOptional(INPUT,'Plot_Atoms',defaultPlot_Atoms);
addOptional(INPUT,'Plot_Bonds',defaultPlot_Bonds);

parse(INPUT,GUI_Inputs_C{:});

Plot_Atoms = INPUT.Results.Plot_Atoms;
Plot_Bonds = INPUT.Results.Plot_Bonds;

%% Main
XYZ       = PDB_Data.XYZ;
Center    = PDB_Data.center;

Carbon_Pos   = XYZ(PDB_Data.AtomSerNo(:,1),:);
Oxygen_Pos   = XYZ(PDB_Data.AtomSerNo(:,2),:);
Nitrogen_Pos = XYZ(PDB_Data.AtomSerNo(:,3),:);

hF = figure; 
hold on

    %% draw bonds
    if Plot_Bonds
        Conn = Connectivity(XYZ);
        gplot3(Conn,XYZ);
    end
    
    %% Draw atoms
    if Plot_Atoms
        plot3(Center(:,1)  ,Center(:,2)  ,Center(:,3)  ,'LineStyle','none','Marker','d','MarkerFaceColor','w')
        plot3(Carbon_Pos(:,1)  ,Carbon_Pos(:,2)  ,Carbon_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','k','MarkerSize',10)
        plot3(Oxygen_Pos(:,1)  ,Oxygen_Pos(:,2)  ,Oxygen_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','r','MarkerSize',10)
        plot3(Nitrogen_Pos(:,1),Nitrogen_Pos(:,2),Nitrogen_Pos(:,3),'LineStyle','none','Marker','o','MarkerFaceColor','b','MarkerSize',10)
    end
hold off

%% figure setting
xlabel('X')
ylabel('Y')
axis image;
rotate3d on