function hF = PlotXYZfiles_AmideI(PDB_Data)
%% PlotXYZfiles
%  
% Given the Stuctural infomation that generated by GetAmideI.m this
% function can plot the molecule and its' amide I modes.
% 
% ------- Version log -----------------------------------------------------
% 
% Ver. 1.4  140605  Readuce the process for reading XYZ data
% 
% Ver. 1.3  131107  Add imput "Rot_Mat" to rotate molecue as user assigned
%                   This is the correction follow by v1.2 of
%                   OneDSFG_AmideI.m
% 
% Ver. 1.2  130930  Move gplot3 from Molecular_Plot to here to accomodate
%                   the update of molecular_plot
% 
% Ver. 1.1  130814  Bug in atom position index fixed 
% 
% Ver. 1.0  130729  Isolated from TwoDSFG_Simulation
% 
% ------------------------------------------------------------------------
% Copyright Jia-Jung Ho, 2013

%% Debug

% PDB_Data    = ConstructGrid('Debug');
% PDB_Data = TwoMolConstruct;
% Orientation = [0,0,0];

%% Read orientation inputs from GUI
% PDB_Data = handles.PDB_Data;

% Phi_D   = str2double(get(handles.Mol_Phi,'String'));
% Psi_D   = str2double(get(handles.Mol_Psi,'String'));
% Theta_D = str2double(get(handles.Mol_Theta,'String'));

Phi_D = 0;
Psi_D = 0;
Theta_D = 0;
Orientation = [Phi_D,Psi_D,Theta_D];

%% Main

% Generate rotation matrix
Orientation = Orientation/180*pi; % turn to radius unit

Phi_Avg   = Orientation(1);
Psi_Avg   = Orientation(2);
Theta_Avg = Orientation(3);

Rot_Mat = R1_ZYZ_0(Phi_Avg,Psi_Avg,Theta_Avg);

% Rotate molecule and transition dipole 
R          = (Rot_Mat * PDB_Data.XYZ')';
Rot_Center = (Rot_Mat * PDB_Data.center')';
Rot_mu     = (Rot_Mat * PDB_Data.mu')';

% Scale TDV vector in plot
Rot_mu_S = Rot_mu./16;

% draw molecule
hF = figure; hold on
Conn = Connectivity(PDB_Data.XYZ);
gplot3(Conn,R);
axis image;
rotate3d on

% Define C,O,N atom position
Carbon_Pos   = R(PDB_Data.AtomSerNo(:,1),:);
Oxygen_Pos   = R(PDB_Data.AtomSerNo(:,2),:);
Nitrogen_Pos = R(PDB_Data.AtomSerNo(:,3),:);


% line(Test_X',Test_Y',Test_Z','LineWidth',2)
quiver3(Rot_Center(:,1),Rot_Center(:,2),Rot_Center(:,3),...
        Rot_mu_S(:,1),Rot_mu_S(:,2),Rot_mu_S(:,3),0,...
        'LineWidth',2,...
        'Color',[0 1 0]);

plot3(Rot_Center(:,1)  ,Rot_Center(:,2)  ,Rot_Center(:,3)  ,'LineStyle','none','Marker','d','MarkerFaceColor','w')
plot3(Carbon_Pos(:,1)  ,Carbon_Pos(:,2)  ,Carbon_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','k','MarkerSize',10)
plot3(Oxygen_Pos(:,1)  ,Oxygen_Pos(:,2)  ,Oxygen_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','r','MarkerSize',10)
plot3(Nitrogen_Pos(:,1),Nitrogen_Pos(:,2),Nitrogen_Pos(:,3),'LineStyle','none','Marker','o','MarkerFaceColor','b','MarkerSize',10)

hold off

xlabel('X')
ylabel('Y')