function Rps0 = JonesTrans1(A_Si)
%JONESTRANS1
%    RPS0 = JONESTRANS1(A_SI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Oct-2017 09:44:12

Rps0 = reshape([cos(A_Si),0.0,0.0,1.0,sin(A_Si),0.0],[2,3]);
