function Rps1 = JonesRef1(A_Si)
%JONESREF1
%    RPS1 = JONESREF1(A_SI)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Dec-2016 15:23:28

Rps1 = reshape([-cos(A_Si),0.0,0.0,1.0,sin(A_Si),0.0],[2,3]);
