function Rps2 = JonesRef2(A_Si,A_Vi)
%JONESREF2
%    RPS2 = JONESREF2(A_SI,A_VI)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Dec-2016 15:23:28

t2 = cos(A_Si);
t3 = cos(A_Vi);
t4 = sin(A_Si);
t5 = sin(A_Vi);
Rps2 = reshape([-t2.*t3,0.0,0.0,0.0,0.0,-t2,0.0,0.0,-t2.*t5,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,t5,0.0,t3.*t4,0.0,0.0,0.0,0.0,t4,0.0,0.0,t4.*t5,0.0,0.0,0.0],[4,9]);
