function Rps2 = JonesTrans2(A_Si,A_Vi)
%JONESTRANS2
%    RPS2 = JONESTRANS2(A_SI,A_VI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jun-2020 08:02:26

t2 = cos(A_Si);
t3 = cos(A_Vi);
t4 = sin(A_Si);
t5 = sin(A_Vi);
Rps2 = reshape([t2.*t3,0.0,0.0,0.0,0.0,t2,0.0,0.0,t2.*t5,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,t5,0.0,t3.*t4,0.0,0.0,0.0,0.0,t4,0.0,0.0,t4.*t5,0.0,0.0,0.0],[4,9]);
