function hF = PlotXYZfiles_Acid(Struc_Data)
%% PlotXYZfiles
%  
% Given the Stuctural infomation that generated by GetAmideI.m this
% function can plot the molecule and its' amide I modes.
% 
% ------- Version log -----------------------------------------------------
% 
% Ver. 1.5  140723  Add hydrogen atom
% 
% Ver. 1.4  140605  Readuce the process for reading XYZ data
% 
% Ver. 1.3  131107  Add imput "Rot_Mat" to rotate molecue as user assigned
%                   This is the correction follow by v1.2 of
%                   OneDSFG_AmideI.m
% 
% Ver. 1.2  130930  Move gplot3 from Molecular_Plot to here to accomodate
%                   the update of molecular_plot
% 
% Ver. 1.1  130814  Bug in atom position index fixed 
% 
% Ver. 1.0  130729  Isolated from TwoDSFG_Simulation
% 
% ------------------------------------------------------------------------
% Copyright Jia-Jung Ho, 2013

%% Debug
% PDB_Data    = GetAcid('Debug');
% Orientation = [0,0,0];

%% Read orientation inputs from GUI
% PDB_Data = handles.PDB_Data;

% Phi_D   = str2double(get(handles.Mol_Phi,'String'));
% Psi_D   = str2double(get(handles.Mol_Psi,'String'));
% Theta_D = str2double(get(handles.Mol_Theta,'String'));
% Orientation = [Phi_D,Psi_D,Theta_D];

%% Main

Num_Modes    = Struc_Data.Num_Modes;
XYZ          = Struc_Data.XYZ;
Center       = Struc_Data.center;
Mu           = Struc_Data.mu;
RamanM       = Struc_Data.alpha_matrix;
Displacement = Struc_Data.Displacement;

hF = figure; 
hold on

    %% draw bonds
    Conn = Connectivity(XYZ);
        % add line between the two Carbon
        Conn(1,5) = 1;
        Conn(5,1) = 1;

    gplot3(Conn,XYZ);
    

    %%  Draw atoms
    %Define C,OD,OS atom position
    Carbon_Pos   = XYZ(Struc_Data.AtomSerNo(:,1),:);
    OxygenD_Pos  = XYZ(Struc_Data.AtomSerNo(:,2),:);
    OxygenS_Pos  = XYZ(Struc_Data.AtomSerNo(:,3),:);
    Hydrogen_Pos = XYZ(Struc_Data.AtomSerNo(:,4),:);
    
    plot3(Center(:,1)  ,Center(:,2)  ,Center(:,3)  ,'LineStyle','none','Marker','d','MarkerFaceColor','w')
    plot3(Carbon_Pos(:,1)  ,Carbon_Pos(:,2)  ,Carbon_Pos(:,3)  ,'LineStyle','none','Marker','o','MarkerFaceColor','k','MarkerSize',10)
    plot3(OxygenD_Pos(:,1) ,OxygenD_Pos(:,2) ,OxygenD_Pos(:,3) ,'LineStyle','none','Marker','o','MarkerFaceColor',[1,0,0],'MarkerSize',10)
    plot3(OxygenS_Pos(:,1) ,OxygenS_Pos(:,2) ,OxygenS_Pos(:,3) ,'LineStyle','none','Marker','o','MarkerFaceColor',[1,0,0],'MarkerSize',10)
    plot3(Hydrogen_Pos(:,1),Hydrogen_Pos(:,2),Hydrogen_Pos(:,3),'LineStyle','none','Marker','o','MarkerFaceColor',[1,1,1],'MarkerSize',10)


    %% draw transition dipoles
%     TDV_Scale = 0.1;
%     Mu_S = TDV_Scale .* Mu; % Scale TDV vector in plot
%     
%     quiver3(Center(:,1),Center(:,2),Center(:,3),...
%             Mu_S(:,1),Mu_S(:,2),Mu_S(:,3),0,...
%             'LineWidth',2,...
%             'Color',[255,128,0]./256);

    %% draw Raman tensor using plot_Raman
%     RT_scale = 2;
%     N_mesh   = 20;
% 
%     for i = 1: Num_Modes
%         Raman  = squeeze(RamanM(i,:,:));
%         plot_Raman(Raman,Center(i,:),RT_scale,N_mesh)
%     end

hold off

%% figure setting 
hAx = findobj(hF,'type','axes');

LL = 5;
Orig_Box = [-LL,LL,-LL,LL,-LL,LL];

XMin = min( Orig_Box(1),Orig_Box(1)+ Displacement(1));
XMax = max( Orig_Box(2),Orig_Box(2)+ Displacement(1));
YMin = min( Orig_Box(3),Orig_Box(3)+ Displacement(2));
YMax = max( Orig_Box(4),Orig_Box(4)+ Displacement(2));
ZMin = min( Orig_Box(5),Orig_Box(5)+ Displacement(3));
ZMax = max( Orig_Box(6),Orig_Box(6)+ Displacement(3));

hAx.XLim = [XMin,XMax];
hAx.YLim = [YMin,YMax];
hAx.ZLim = [ZMin,ZMax];

rotate3d on
grid on


xlabel('X')
ylabel('Y')
zlabel('Z')

view([0,0])
