function hF = PlotXYZfiles_TCO(hAx,SData)
%% PlotXYZfiles
%  
% Given the Stuctural infomation that generated by GetAmideI.m this
% function can plot the molecule and its' amide I modes.
% 
% ------- Version log -----------------------------------------------------
% 
% Ver. 1.5  140723  Add hydrogen atom
% 
% Ver. 1.4  140605  Readuce the process for reading XYZ data
% 
% Ver. 1.3  131107  Add imput "Rot_Mat" to rotate molecue as user assigned
%                   This is the correction follow by v1.2 of
%                   OneDSFG_AmideI.m
% 
% Ver. 1.2  130930  Move gplot3 from Molecular_Plot to here to accomodate
%                   the update of molecular_plot
% 
% Ver. 1.1  130814  Bug in atom position index fixed 
% 
% Ver. 1.0  130729  Isolated from TwoDSFG_Simulation
% 
% ------------------------------------------------------------------------
% Copyright Jia-Jung Ho, 2013

%% Debug
% PDB_Data    = GetAcid('Debug');
% Orientation = [0,0,0];

%% Input parser
GUI_Inputs = SData.GUI_Inputs;
GUI_Inputs_C      = fieldnames(GUI_Inputs);
GUI_Inputs_C(:,2) = struct2cell(GUI_Inputs);
GUI_Inputs_C      = GUI_Inputs_C';

INPUT = inputParser;
INPUT.KeepUnmatched = 1;

% Default values
defaultPlot_Atoms = 1;
defaultPlot_Bonds = 1;
defaultPlot_Axis  = 1;
defaultPhi        = 0;
defaultPsi        = 0;
defaultTheta      = 0;

% Add optional inputs to inputparser object
addOptional(INPUT,'Plot_Atoms',defaultPlot_Atoms);
addOptional(INPUT,'Plot_Bonds',defaultPlot_Bonds);
addOptional(INPUT,'Plot_Axis' ,defaultPlot_Axis );
addOptional(INPUT,'Phi'       ,defaultPhi       );
addOptional(INPUT,'Psi'       ,defaultPsi       );
addOptional(INPUT,'Theta'     ,defaultTheta     );

parse(INPUT,GUI_Inputs_C{:});

Plot_Atoms = INPUT.Results.Plot_Atoms;
Plot_Bonds = INPUT.Results.Plot_Bonds;
Plot_Axis  = INPUT.Results.Plot_Axis;
Phi        = INPUT.Results.Phi;
Psi        = INPUT.Results.Psi;
Theta      = INPUT.Results.Theta;

%% Rotate the molecule to Lab frame
XYZ       = SData.XYZ;
AtomName  = SData.AtomName;
LocCenter = SData.LocCenter;

%% Define C,OD,OS atom position
% Prep hAx 
if ~ishandle(hAx)
    hF = figure; 
    hAx = axes('Parent',hF);
else
    hF = hAx.Parent;
end

hold(hAx,'on')
    %% draw a line connection the two oscillator
    Conn = zeros(SData.NAtoms);
    Conn(1,5)=1;
    Conn = Conn|Conn';
    gplot3(Conn,XYZ,'LineWidth',1,'Color',[0.3,0.3,0.3],'Parent',hAx);
    %% draw bonds
    if Plot_Bonds
        Conn = SD_Connectivity(SData);
        % add line between the two Carbon
        Conn(1,4) = 0;
        Conn(5,8) = 0;
        Conn = Conn&Conn';

        gplot3(Conn,XYZ,'LineWidth',5,'Color',[0.3,0.3,0.3],'Parent',hAx);
    end
    %%  Draw atoms
    if Plot_Atoms
        plot3(hAx,LocCenter(:,1)  ,LocCenter(:,2)  ,LocCenter(:,3)  ,'LineStyle','none','Marker','d','MarkerFaceColor','w','MarkerSize',10)
        
        C_Ind = strcmp(AtomName,'C');
        O_Ind = strcmp(AtomName,'O');
        H_Ind = strcmp(AtomName,'H');
        XYZ_C = XYZ(C_Ind,:);
        XYZ_O = XYZ(O_Ind,:);
        XYZ_H = XYZ(H_Ind,:);
             
        PlotAtom(hAx,'C',XYZ_C);
        PlotAtom(hAx,'O',XYZ_O);
        PlotAtom(hAx,'H',XYZ_H);
        
    end

    %% Draw molecular and Lab frame
    if Plot_Axis
        Lab_Frame = [1,0,0;
                     0,1,0;
                     0,0,1 ];
        
        R_MF_LF = R1_ZYZ_0(Phi/180*pi,Psi/180*pi,Theta/180*pi);
        PlotRotMolFrame(hAx,Lab_Frame,R_MF_LF,[0,0,0])
    end
    
hold(hAx,'off')

    
%% figure setting 
hAx.XLabel.String = 'X';
hAx.YLabel.String = 'Y';
hAx.ZLabel.String = 'Z';
axis(hAx,'image');
rotate3d(hAx,'on')
grid(hAx,'on')
view(hAx,[50,10])
axis(hAx,'image');
camlight
daspect([1 1 1]);
    
