function R1_zyx = R1_zyx_0(D_X,D_Y,D_Z)
%R1_ZYX_0
%    R1_ZYX = R1_ZYX_0(D_X,D_Y,D_Z)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Oct-2016 16:46:36

t2 = cos(D_X);
t3 = sin(D_X);
t4 = sin(D_Z);
t5 = cos(D_Z);
t6 = sin(D_Y);
t7 = cos(D_Y);
R1_zyx = reshape([t2.*t7,t3.*t7,t6,-t3.*t5+t2.*t4.*t6,t2.*t5+t3.*t4.*t6,-t4.*t7,-t3.*t4-t2.*t5.*t6,t2.*t4-t3.*t5.*t6,t5.*t7],[3,3]);
