function R1_ZYZ_12 = R1_ZYZ_12(Theta)
%R1_ZYZ_12
%    R1_ZYZ_12 = R1_ZYZ_12(THETA)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    08-Nov-2014 13:24:16

R1_ZYZ_12 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cos(Theta)],[3, 3]);
