function R1_ZYZ_1 = R1_ZYZ_1(Psi,Theta)
%R1_ZYZ_1
%    R1_ZYZ_1 = R1_ZYZ_1(PSI,THETA)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    08-Nov-2014 13:24:16

t2 = sin(Theta);
R1_ZYZ_1 = reshape([0.0,0.0,-t2.*cos(Psi),0.0,0.0,t2.*sin(Psi),0.0,0.0,cos(Theta)],[3, 3]);
