function R2_ZYZ = R2_ZYZ_0(Phi,Psi,Theta)
%R2_ZYZ_0
%    R2_ZYZ = R2_ZYZ_0(PHI,PSI,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Jan-2017 22:28:37

t3 = cos(Psi);
t4 = sin(Phi);
t5 = cos(Phi);
t6 = cos(Theta);
t7 = sin(Psi);
t8 = t4.*t7;
t9 = t3.*t5.*t6;
t2 = t8-t9;
t10 = t3.*t4;
t11 = t5.*t6.*t7;
t12 = t10+t11;
t13 = t2.*t12;
t14 = sin(Theta);
t15 = t5.*t7;
t16 = t3.*t4.*t6;
t17 = t15+t16;
t18 = t3.*t5;
t20 = t4.*t6.*t7;
t19 = t18-t20;
t21 = t14.^2;
t22 = t5.*t14.*t17;
t23 = t5.*t14.*t19;
t24 = t4.*t5.*t21;
t25 = t17.*t19;
t26 = t4.*t14.*t17;
t27 = t4.*t14.*t19;
t28 = t2.*t3.*t14;
t29 = t3.*t12.*t14;
t30 = t5.*t7.*t21;
t31 = t5.*t6.*t14;
t32 = t7.*t14.*t17;
t33 = t7.*t14.*t19;
t34 = t4.*t7.*t21;
t35 = t6.*t17;
t36 = t6.*t19;
t37 = t4.*t6.*t14;
t38 = t6.*t7.*t14;
R2_ZYZ = reshape([t2.^2,-t2.*t17,t28,-t2.*t17,t17.^2,-t3.*t14.*t17,t28,-t3.*t14.*t17,t3.^2.*t21,t13,-t2.*t19,-t2.*t7.*t14,-t12.*t17,t25,t32,t29,-t3.*t14.*t19,-t3.*t7.*t21,-t2.*t5.*t14,-t2.*t4.*t14,-t2.*t6,t22,t26,t35,-t3.*t5.*t21,-t3.*t4.*t21,-t3.*t6.*t14,t13,-t12.*t17,t29,-t2.*t19,t25,-t3.*t14.*t19,-t2.*t7.*t14,t32,-t3.*t7.*t21,t12.^2,-t12.*t19,-t7.*t12.*t14,-t12.*t19,t19.^2,t33,-t7.*t12.*t14,t33,t7.^2.*t21,-t5.*t12.*t14,-t4.*t12.*t14,-t6.*t12,t23,t27,t36,t30,t34,t38,-t2.*t5.*t14,t22,-t3.*t5.*t21,-t2.*t4.*t14,t26,-t3.*t4.*t21,-t2.*t6,t35,-t3.*t6.*t14,-t5.*t12.*t14,t23,t30,-t4.*t12.*t14,t27,t34,-t6.*t12,t36,t38,t5.^2.*t21,t24,t31,t24,t4.^2.*t21,t37,t31,t37,t6.^2],[9,9]);
