function R1_Quad = R1_Quad(a,b,c,d)
%R1_QUAD
%    R1_QUAD = R1_QUAD(A,B,C,D)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    23-Oct-2016 21:17:23

t2 = b.*c.*2.0;
t3 = a.^2;
t4 = b.^2;
t5 = c.^2;
t6 = d.^2;
t7 = a.*c.*2.0;
t8 = b.*d.*2.0;
t9 = c.*d.*2.0;
R1_Quad = reshape([t3+t4-t5-t6,t2+a.*d.*2.0,-t7+t8,t2-a.*d.*2.0,t3-t4+t5-t6,t9+a.*b.*2.0,t7+t8,t9-a.*b.*2.0,t3-t4-t5+t6],[3, 3]);
